#cloud-config
users:
  - name: {{VM_USER}}
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true

package_update: true
package_upgrade: true

packages:
  - git
  - wget
  - curl
  - vim
  - btop
  - fzf
  - tmux
  - nvtop
  - tree
  - ubuntu-drivers-common
  - gcsfuse

write_files:
  - path: /etc/sysctl.d/99-swappiness.conf
    content: |
      vm.swappiness=10
  - path: /etc/ssh/sshd_config.d/99-custom.conf
    content: |
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      PubkeyAuthentication yes
      PermitRootLogin no

runcmd:
  # Install GCS FUSE Repo
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
  - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt gcsfuse-$(lsb_release -c -s) main" | tee /etc/apt/sources.list.d/gcsfuse.list
  - apt-get update && apt-get install -y gcsfuse
  
  - ubuntu-drivers autoinstall >> /var/log/gpu-driver-install.log 2>&1
  - sysctl -p /etc/sysctl.d/99-swappiness.conf
  - curl -LsSf https://astral.sh/uv/install.sh | sudo -u {{VM_USER}} sh
  - echo 'source /usr/share/doc/fzf/examples/key-bindings.bash' >> /home/{{VM_USER}}/.bashrc
  - chown {{VM_USER}}:{{VM_USER}} /home/{{VM_USER}}/.bashrc
  - systemctl reload ssh